# Generated by Django 3.2.2 on 2023-12-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_profile_ktdivp', upload_to='images/'),
        ),
    ]
