# Generated by Django 3.2.23 on 2023-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleinstance',
            name='time_taken',
            field=models.DurationField(null=True),
        ),
    ]
