# Generated by Django 3.2.23 on 2023-12-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_alter_puzzleinstance_time_taken'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='puzzleinstance',
            index=models.Index(fields=['-time_taken'], name='puzzles_puz_time_ta_eddf16_idx'),
        ),
    ]
