# Generated by Django 3.2.23 on 2023-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_puzzleinstance_puzzles_puz_time_ta_eddf16_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='puzzleinstance',
            name='puzzles_puz_time_ta_eddf16_idx',
        ),
        migrations.AddIndex(
            model_name='puzzleinstance',
            index=models.Index(fields=['time_taken'], name='puzzles_puz_time_ta_b35bba_idx'),
        ),
    ]
