# Generated by Django 3.2.23 on 2023-12-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_alter_puzzleinstance_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleinstance',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
