# Generated by Django 3.2.23 on 2023-12-06 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0005_puzzleinstance_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleinstance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_instances', to='auth.user'),
            preserve_default=False,
        ),
    ]
