# Generated by Django 3.2.2 on 2024-01-02 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0005_alter_puzzleinstance_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleinstance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
