# Generated by Django 3.2.2 on 2024-01-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_profile', '0001_initial'),
        ('puzzles', '0006_alter_puzzleinstance_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleinstance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_instances', to='player_profile.playerprofile'),
        ),
    ]
